# Site
name: "Narendhiran'S"
description: "An Armchair marketer's hustles and opinions"
meta_description: "An Armchair marketer's hustles and opinions"
logo: 'assets/images/logo1.png'
favicon: 'assets/images/Favicon.ico'
baseurl: /
google_analytics: ''
disqus: ''
mailchimp-list: ''

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: f767c2b5c1184982344ced80f8712a81
    email: narendhiran.s@gmail.com
    web: https://www.linkedin.com/in/narendhiran-s/ 
    twitter: https://twitter.com/s_narendhiran
    description: "Entrepreneur, full-stack marketer, occasional techie."
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
