# Site
name: "narenism"
description: "gospels of an armchair marketer"
meta_description: "gospels of an armchair marketer"
logo: 'assets/images/logo1.png'
favicon: 'assets/images/Favicon.ico'
baseurl: /
google_analytics: ''
disqus: ''
mailchimp-list: ''

# Authors
authors:
  naren:
    name: naren
    display_name: Narendhiran S
    gravatar: f767c2b5c1184982344ced80f8712a81
    email: narendhiran.s@gmail.com
    web: https://www.linkedin.com/in/narendhiran-s/ 
    twitter: https://twitter.com/s_narendhiran
    description: "Entrepreneur, full-stack marketer with 4+ years of experience in designing & delivering marketing campaigns
from concept to execution in both B2B (SaaS) & B2C spaces."
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
